---
- hosts: aws-host
  become: true
  tasks:
    - name: Update apt repo and install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Add user to the Docker group
      user:
        name: ubuntu
        groups: docker

    - name: Pull Docker image
      docker_image:
        name: sanjaykshebbar/asi-insurance-app
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: asi-app
        image: sanjaykshebbar/asi-insurance-app:latest
        state: started
        ports:
          - "80:8080"
