---
- name: Deploy Docker Container on EC2
  hosts: webserver
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        group: docker

    - name: Pull Docker image
      docker_image:
        name: "sanjaykshebbar/asi-insurance-app"
        tag: "latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "asi-insurance-app"
        image: "sanjaykshebbar/asi-insurance-app:latest"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
